services:
    php:
        container_name: well_php
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./docker-compose/php/Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - './:/var/www'
        networks:
            - well_backend
        depends_on:
            - mysql
            - redis
    mysql:
        container_name: well_mysql
        restart: unless-stopped
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./docker-compose/db/mysql:/docker-entrypoint-initdb.d
        networks:
            - well_backend
    nginx:
        container_name: well_nginx
        restart: unless-stopped
        image: nginx:1.17-alpine
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - well_backend
    redis:
        container_name: well_redis
        restart: unless-stopped
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        networks:
            - well_backend
networks:
    well_backend:
        driver: bridge
